spring.application.name=backend

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ai_placement_assistant
spring.datasource.username=aman
spring.datasource.password=Amankumar@123

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
